languageCode = "zh-cn"
languageName = "简体中文"
weight = 4
title = "Eecho"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = ""
  description = "Eecho 的个人博客"

[params.author]
  name = "Eecho"
  image = "/img.jpg"
  headline = "记录与分享"
  bio = "热爱技术与生活。"
  links = [
    { github = "https://github.com/EechoAis" }
  ]